---
trust-domain: xpi
treeherder:
    group-names:
        'B': 'Builds'
        'T': 'Tests'

task-priority: lowest

taskgraph:
    register: xpi_taskgraph:register
    repositories:
        xpi:
            name: "XPI source"
    cached-task-prefix: xpi.test-xpi-public

workers:
    aliases:
        b-linux:
            provisioner: aws-provisioner-v1
            implementation: docker-worker
            os: linux
            worker-type: 'xpi-{level}-b-linux'

# Uncomment if this is a private repo
# github_clone_secret: project/xpi/xpi-github-clone-ssh
